server:
  port: 19091

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**

        - id: performance-service
          uri: lb://performance-service
          predicates:
            - Path=/api/v1/performance/**

        - id: reservation-payment-service
          uri: lb://reservation-payment-service
          predicates:
            - Path=/api/v1/reservations/**
            - Path=/api/v1/payment/**

        - id: ticket-service
          uri: lb://ticket-service
          predicates:
            - Path=/api/v1/ticket/**

      discovery:
        locator:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/


service:
  jwt:
    secret-key: "c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXNwYXJ0YS1ib290Y2FtcC1jaDItc3BhcnRhLWxvZ2lzdGljcy1tYWRlLWJ5LWphYmJlcndvY2tlcjA0"