server:
  port: 19091

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**

        - id: performance-service
          uri: lb://performance-service
          predicates:
            - Path=/api/v1/performances/**, /api/v1/categories/**, /api/v1/timetables/**, /api/v1/seats/**

        - id: reservation-payment-service
          uri: lb://reservation-payment-service
          predicates:
            - Path=/api/v1/reservations/**, /api/v1/payments/**

        - id: ticket-service
          uri: lb://ticket-service
          predicates:
            - Path=/api/v1/tickets/**

        - id: coupon-service
          uri: lb://coupon-service
          predicates:
            - Path=/api/v1/coupons/**

        - id: queue-service
          uri: lb://queue-service
          predicates:
            - Path=/api/v1/queues/**

      discovery:
        locator:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  metrics:
    enable:
      all: true


service:
  jwt:
    secret-key: ${SECRET_KEY}