name: Main Workflow

on:
  push:
    branches: [ feat/#39-distribution ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout all submodules
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Run module workflows
        run: |
          echo "Triggering coupon workflow..."
          response=$(curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/Sparta-Triple/CultureTicket/actions/workflows/coupon-github-action.yml/dispatches \
            -d '{"ref":"feat/#39-distribution"}'

          echo "Triggering gateway workflow..."
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/Sparta-Triple/CultureTicket/actions/workflows/gateway-github-action.yml/dispatches \
            -d '{"ref":"feat/#39-distribution"}'

          echo "Triggering gateway workflow..."
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/Sparta-Triple/CultureTicket/actions/workflows/performance-github-action.yml/dispatches \
            -d '{"ref":"feat/#39-distribution"}'
          
          echo "Triggering gateway workflow..."
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/Sparta-Triple/CultureTicket/actions/workflows/queue-github-action.yml/dispatches \
            -d '{"ref":"feat/#39-distribution"}'
          
          echo "Triggering gateway workflow..."
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/Sparta-Triple/CultureTicket/actions/workflows/reservation-github-action.yml/dispatches \
            -d '{"ref":"feat/#39-distribution"}'
          
          echo "Triggering gateway workflow..."
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/Sparta-Triple/CultureTicket/actions/workflows/ticket-github-action.yml/dispatches \
            -d '{"ref":"feat/#39-distribution"}'
          
          echo "Triggering gateway workflow..."
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/Sparta-Triple/CultureTicket/actions/workflows/user-github-action.yml/dispatches \
            -d '{"ref":"feat/#39-distribution"}'
          
          echo "Triggering gateway workflow..."
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/Sparta-Triple/CultureTicket/actions/workflows/server-github-action.yml/dispatches \
            -d '{"ref":"feat/#39-distribution"}'
          
          echo "Response: $response"